### ISSUE TITLE
Danish file names (æøå)

### ISSUE THREAD

**Issue by klausnitzer** [bruot/pyrmexplorer#6]
Hi there filenames shown in the explorer and the files downloaded do not support danish character.

Any advise how to fix it? I guess it has something to do with:

```
rmexplorerwindow.py
res.info().get_content_charset()
```

**Comment by bruot** [comment]
Thanks for the report. This doesn't surprise me... I have already seen strange behaviour of this `get_content_charset()` probably because of the little web server that is on the tablet that doesn't always provide an encoding.
 
It will take some time until I will be able to look at this (busy with other stuff). In the meantime, it would be useful to post here:
- Version of the software on the tablet
- How are these characters displayed in the explorer (screenshot)?
- What is returned by `res.info.get_content_charset()`?

**Comment by bruot** [comment]
Fixed by 6edbc540eb0630034ca8473fe236082f3d164128.
