### ISSUE TITLE
Window Size

### ISSUE THREAD

**Issue by nasendackel** [bruot/pyrmexplorer#7]
Hi, once again: Thanks for this great tool. 

I had the problem, that the window opens very small on my surface. So I add:
`self.width = 1200
        self.height = 1000
        self.left =650
        self.top = 400
        self.setGeometry(self.left,self.top,self.width, self.height)`
Because my python skill are very limited, maybe there is a better way like remembering the windows size.

**Comment by bruot** [comment]
Hello. It is quite possible the Qt library that handles the graphic windows fails to set an appropriate size. However, it is probably better to let Qt try to do its best rather than reinventing the wheel and rewriting new rules in rMExplorer to handle that.

To fix what are likely to be edge cases, I could add launch arguments to rMExplorer that allow users to fix the size at startup if necessary.

**Comment by nasendackel** [comment]
That would be nice idea. Thanks.

**Comment by bruot** [comment]
Fixed by 2c8986197c5a490681a9cfa60cb1d84f4e470fef.

You can now launch rMExplorer with commands such as:
`python -m rmexplorer --geometry 50x50x800x300`
`rmexplorer.exe --geometry 50x50x800x300`
These can be written in an alias in .bashrc, in a Windows shortcut path, etc.

**Comment by nasendackel** [comment]
Perfect! Works fine. Thanks!
